export const authConstants = {
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_FILURE: "SIGNIN_FILURE",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",

    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_FILURE: "SIGNUP_FILURE",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",

    GETALLCATEGORY_SUCCESS: "GETALLCATEGORY_SUCCESS",
    GETALLCATEGORY_FILURE: "GETALLCATEGORY_FILURE",

    CATEGORY_FILURE: "CATEGORY_FILURE",
    CATEGORY_SUCCESS: "CATEGORY_SUCCESS",

    
    DELETECATEGORY_SUCCESS: "DELETECATEGORY_SUCCESS",
    DELETECATEGORY_FILURE: "DELETECATEGORY_FILURE",


    PRODUCT_FILURE: "PRODUCT_FILURE",
    PRODUCT_SUCCESS: "PRODUCT_SUCCESS",


    GETALLPRODUCTS_FILURE: "GETALLPRODUCTS_FILURE",
    GETALLPRODUCTS_SUCCESS: "GETALLPRODUCTS_SUCCESS",


    UPDATEPRODUCTS_FILURE: "UPDATEPRODUCTS_FILURE",
    UPDATEPRODUCTS_SUCCESS: "UPDATEPRODUCTS_SUCCESS",


    NEWPAGE_FILURE: "NEWPAGE_FILURE",
    NEWPAGE_SUCCESS: "NEWPAGE_SUCCESS",

    GETNEWPAGE_FILURE: "GETNEWPAGE_FILURE",
    GETNEWPAGE_SUCCESS: "GETNEWPAGE_SUCCESS",

    GATALLHIGHLIGHT_FILURE: "GATALLHIGHLIGHT_FILURE",
    GATALLHIGHLIGHT_SUCCESS: "GATALLHIGHLIGHT_SUCCESS",
}

